services:

  postgres:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: airflow_user
      POSTGRES_PASSWORD: airflow_password
      POSTGRES_DB: airflow_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U airflow_user -d airflow_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:2.7.2
    container_name: airflow_container
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:airflow_password@postgres_container:5432/airflow_db
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow_user:airflow_password@postgres_container:5432/airflow_db
      - AIRFLOW__WEBSERVER__EXPOSE_CONFIG=True
      - AIRFLOW__LOGGING__LOGGING_LEVEL=DEBUG
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./logs:/opt/airflow/logs
    depends_on:
      postgres:
        condition: service_healthy
    command: >
      bash -c "
      until airflow db check; do
        echo 'Waiting for database to be ready...';
        sleep 5;
      done &&
      airflow db init &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      (airflow webserver --port 8080 & airflow scheduler)
      "

volumes:
  postgres_data:
